import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { SpeedInsights } from "@vercel/speed-insights/next";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import { perks } from "@/components/ui/perks";
import { Providers } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={cn("relative h-full font-sans antialiased", inter.className)}>
          <main className="relative flex flex-col min-h-screen">
            <Providers>
            <Navbar />
            <div className="flex-grow flex-1">{children}</div>
            <SpeedInsights />
            <section className="border-t border-gray-200 bg-gray-100">
              <MaxWidthWrapper className="py-10">
                <div className="grid grid-cols-1 gap-y-12 sm:grid-cols-2 sm:gap-x-6 lg:grid-cols-3 lg:gap-x-4 lg:gap-y-0">
                  {perks.map((perk) => (
                    <div key={perk.name} className="text-center md:flex md:items-start md:text-left lg:block lg:text-center">
                      <div className="'md:flex-shrink-0 flex justify-center">
                        <div className="h-16 w-16 flex items-center justify-center rounded-full bg-orange-100 text-orange-600">
                          <perk.Icon className="w-1/3 h-1/3" />
                        </div>
                      </div>
                      <div className="mt-6 md:ml-4 md:mt-0 lg:ml-0 lg:mt-6">
                        <h3 className="text-base font-medium text-gray-900">
                          {perk.name}</h3>
                        <p className="mt-3 text-sm text-muted-foreground">
                          {perk.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </MaxWidthWrapper>
            </section>
            </Providers>
          </main>
      </body>
    </html>
  );
}
